# Generated by Django 5.1.4 on 2025-05-28 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreSysteme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cle', models.CharField(max_length=255, unique=True)),
                ('valeur', models.TextField()),
                ('type_valeur', models.CharField(choices=[('STRING', 'Chaîne'), ('INTEGER', 'Entier'), ('DECIMAL', 'Décimal'), ('BOOLEAN', 'Booléen'), ('JSON', 'JSON'), ('DATE', 'Date'), ('DATETIME', 'Date et heure')], max_length=20)),
                ('categorie', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('valeur_par_defaut', models.TextField(blank=True)),
                ('modifiable', models.BooleanField(default=True)),
                ('visible_interface', models.BooleanField(default=True)),
                ('validation_regex', models.CharField(blank=True, max_length=500)),
                ('valeur_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valeur_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètre Système',
                'verbose_name_plural': 'Paramètres Système',
                'db_table': 'parametres_systeme',
            },
        ),
    ]
