# Generated by Django 5.1.4 on 2025-05-28 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_transaction', models.CharField(choices=[('ACHAT', 'Achat'), ('RETRAIT', 'Retrait'), ('RECHARGE', 'Recharge'), ('TRANSFERT', 'Transfert')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=15)),
                ('merchant_id', models.CharField(blank=True, max_length=100)),
                ('merchant_nom', models.CharField(blank=True, max_length=255)),
                ('terminal_id', models.CharField(blank=True, max_length=100)),
                ('reference_externe', models.CharField(blank=True, max_length=100)),
                ('reference_interne', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('localisation', models.CharField(blank=True, max_length=255)),
                ('coordonnees_gps', models.CharField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDEE', 'Validée'), ('ECHOUEE', 'Échouée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=20)),
                ('code_erreur', models.CharField(blank=True, max_length=50)),
                ('message_erreur', models.TextField(blank=True)),
                ('frais_transaction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taux_change', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('donnees_brutes', models.JSONField(blank=True, default=dict)),
                ('signature_transaction', models.CharField(blank=True, max_length=255)),
                ('agent_validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartes.carterfid')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Rechargement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant_recharge', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE_BANCAIRE', 'Carte bancaire'), ('VIREMENT', 'Virement'), ('MOBILE_MONEY', 'Mobile Money')], max_length=20)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('operateur_mobile', models.CharField(blank=True, max_length=50)),
                ('numero_mobile', models.CharField(blank=True, max_length=20)),
                ('banque_emettrice', models.CharField(blank=True, max_length=100)),
                ('numero_compte', models.CharField(blank=True, max_length=50)),
                ('point_recharge', models.CharField(max_length=255)),
                ('commission_prelevee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut_paiement', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ECHEC', 'Échec'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=20)),
                ('date_rechargement', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('recu_numero', models.CharField(max_length=100, unique=True)),
                ('donnees_paiement', models.JSONField(blank=True, default=dict)),
                ('agent_operateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechargements_operes', to=settings.AUTH_USER_MODEL)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartes.carterfid')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechargements_effectues', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Rechargement',
                'verbose_name_plural': 'Rechargements',
                'db_table': 'rechargements',
            },
        ),
    ]
