# Generated by Django 4.2 on 2025-06-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_carte_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='devise',
            field=models.CharField(default='Ar', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
