# Generated by Django 4.2 on 2025-06-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_devise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='terminal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
