# Generated by Django 4.2 on 2025-06-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_terminal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='localisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
