# Generated by Django 4.2 on 2025-06-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_localisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='code_erreur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='message_erreur',
            field=models.TextField(blank=True, null=True),
        ),
    ]
