# Generated by Django 4.2 on 2025-06-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_code_erreur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='donnees_brutes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
