# Generated by Django 4.2 on 2025-06-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_donnees_brutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargement',
            name='donnees_paiement',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coordonnees_gps',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
