# Generated by Django 5.1.4 on 2025-05-28 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentIdentite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_document', models.CharField(choices=[('CNI_RECTO', 'CNI Recto'), ('CNI_VERSO', 'CNI Verso'), ('PASSEPORT', 'Passeport'), ('PERMIS_RECTO', 'Permis Recto'), ('PERMIS_VERSO', 'Permis Verso'), ('JUSTIFICATIF_DOMICILE', 'Justificatif de domicile'), ('PHOTO_IDENTITE', "Photo d'identité")], max_length=50)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('chemin_fichier', models.TextField()),
                ('taille_fichier', models.BigIntegerField()),
                ('type_mime', models.CharField(max_length=100)),
                ('hash_fichier', models.CharField(max_length=255, unique=True)),
                ('statut_verification', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VERIFIE', 'Vérifié'), ('REJETE', 'Rejeté'), ('EXPIRE', 'Expiré')], default='EN_ATTENTE', max_length=20)),
                ('commentaire_verification', models.TextField(blank=True)),
                ('date_expiration_document', models.DateField(blank=True, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('donnees_ocr', models.JSONField(blank=True, default=dict)),
                ('niveau_confidentialite', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNE', 'Interne'), ('CONFIDENTIEL', 'Confidentiel'), ('SECRET', 'Secret')], default='INTERNE', max_length=20)),
                ('agent_verificateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='identites.entreprise')),
                ('personne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='identites.personne')),
            ],
            options={
                'verbose_name': "Document d'identité",
                'verbose_name_plural': "Documents d'identité",
                'db_table': 'documents_identite',
            },
        ),
    ]
