# Generated by Django 5.1.4 on 2025-05-28 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('organisation', models.CharField(blank=True, max_length=255)),
                ('contact_technique', models.CharField(blank=True, max_length=255)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('type_client', models.CharField(choices=[('PUBLIC', 'Public'), ('CONFIDENTIEL', 'Confidentiel'), ('INTERNE', 'Interne')], max_length=20)),
                ('niveau_acces', models.CharField(choices=[('LECTURE', 'Lecture'), ('ECRITURE', 'Écriture'), ('ADMIN', 'Administrateur')], max_length=20)),
                ('scopes_autorises', models.JSONField(blank=True, default=list)),
                ('adresses_ip_autorisees', models.JSONField(blank=True, default=list)),
                ('rate_limit_par_minute', models.IntegerField(default=60)),
                ('rate_limit_par_jour', models.IntegerField(default=10000)),
                ('webhook_url', models.URLField(blank=True, max_length=500)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('derniere_utilisation', models.DateTimeField(blank=True, null=True)),
                ('nombre_requetes_total', models.BigIntegerField(default=0)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client API',
                'verbose_name_plural': 'Clients API',
                'db_table': 'api_clients',
            },
        ),
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=255)),
                ('methode_http', models.CharField(max_length=10)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('parametres_requete', models.JSONField(blank=True, default=dict)),
                ('corps_requete', models.TextField(blank=True)),
                ('code_reponse', models.IntegerField()),
                ('taille_reponse', models.IntegerField(default=0)),
                ('duree_traitement', models.IntegerField()),
                ('erreur_message', models.TextField(blank=True)),
                ('carte_concernee', models.CharField(blank=True, max_length=100)),
                ('montant_transaction', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_requete', models.DateTimeField(auto_now_add=True)),
                ('trace_id', models.CharField(blank=True, max_length=100)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_management.apiclient')),
            ],
            options={
                'verbose_name': 'Log API',
                'verbose_name_plural': 'Logs API',
                'db_table': 'api_logs',
                'indexes': [models.Index(fields=['client', 'date_requete'], name='api_logs_client__497102_idx'), models.Index(fields=['endpoint', 'date_requete'], name='api_logs_endpoin_00a180_idx'), models.Index(fields=['code_reponse', 'date_requete'], name='api_logs_code_re_64faf0_idx')],
            },
        ),
    ]
