# Generated by Django 4.2 on 2025-06-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='adresse_siege',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='date_creation_entreprise',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_naissance',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
