# Generated by Django 4.2 on 2025-06-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identites', '0002_alter_entreprise_adresse_siege_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('OPERATEUR', 'Opérateur'), ('AGENT', 'Agent'), ('SUPERVISEUR', 'Superviseur'), ('Client', 'Client')], max_length=50),
        ),
    ]
