# Generated by Django 5.1.4 on 2025-05-28 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteRFID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_uid', models.CharField(max_length=100, unique=True)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('type_carte', models.CharField(choices=[('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('ENTREPRISE', 'Entreprise')], max_length=20)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('plafond_quotidien', models.DecimalField(decimal_places=2, max_digits=15)),
                ('plafond_mensuel', models.DecimalField(decimal_places=2, max_digits=15)),
                ('solde_maximum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOQUEE', 'Bloquée'), ('EXPIREE', 'Expirée'), ('PERDUE', 'Perdue'), ('VOLEE', 'Volée')], default='ACTIVE', max_length=20)),
                ('motif_blocage', models.TextField(blank=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateField()),
                ('lieu_emission', models.CharField(max_length=255)),
                ('derniere_utilisation', models.DateTimeField(blank=True, null=True)),
                ('nombre_transactions', models.IntegerField(default=0)),
                ('version_securite', models.CharField(max_length=20)),
                ('cle_chiffrement', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('agent_emission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='identites.entreprise')),
                ('personne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='identites.personne')),
            ],
            options={
                'verbose_name': 'Carte RFID',
                'verbose_name_plural': 'Cartes RFID',
                'db_table': 'cartes_rfid',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatutsCarte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ancien_statut', models.CharField(max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('motif_changement', models.TextField()),
                ('commentaire', models.TextField(blank=True)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('donnees_supplementaires', models.JSONField(blank=True, default=dict)),
                ('agent_modificateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartes.carterfid')),
            ],
            options={
                'verbose_name': 'Historique Statut Carte',
                'verbose_name_plural': 'Historiques Statuts Cartes',
                'db_table': 'historique_statuts_cartes',
            },
        ),
    ]
