# Generated by Django 4.2.7 on 2025-05-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carterfid',
            name='statut',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BLOQUEE', 'Bloquée'), ('EXPIREE', 'Expirée'), ('PERDUE', 'Perdue'), ('VOLEE', 'Volée'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=20),
        ),
    ]
