# Generated by Django 4.2 on 2025-05-31 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identites', '0001_initial'),
        ('cartes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carterfid',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartes_rfid', to='identites.entreprise'),
        ),
        migrations.AlterField(
            model_name='carterfid',
            name='personne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartes_rfid', to='identites.personne'),
        ),
        migrations.AlterField(
            model_name='carterfid',
            name='statut',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BLOQUEE', 'Bloquée'), ('EXPIREE', 'Expirée'), ('PERDUE', 'Perdue'), ('VOLEE', 'Volée'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historiquestatutscarte',
            name='adresse_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
