# Generated by Django 5.1.7 on 2025-05-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0002_alter_carterfid_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquestatutscarte',
            name='adresse_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiquestatutscarte',
            name='motif_changement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiquestatutscarte',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
