# Generated by Django 5.1.4 on 2025-06-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0002_alter_carterfid_entreprise_alter_carterfid_personne_and_more'),
        ('cartes', '0003_alter_historiquestatutscarte_adresse_ip_and_more'),
    ]

    operations = [
    ]
