# Generated by Django 4.2 on 2025-05-31 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0002_alter_carterfid_entreprise_alter_carterfid_personne_and_more'),
        ('cartes', '0003_alter_historiquestatutscarte_adresse_ip_and_more'),
    ]

    operations = [
    ]
