# Generated by Django 4.2 on 2025-06-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0004_merge_20250531_1324'),
        ('cartes', '0004_merge_20250602_0901'),
    ]

    operations = [
    ]
