# Generated by Django 5.1.4 on 2025-05-28 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('SUCCESS', 'Succès')], max_length=20)),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push'), ('INTERNE', 'Interne')], max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('donnees_contexte', models.JSONField(blank=True, default=dict)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='NORMALE', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec'), ('LU', 'Lu')], default='EN_ATTENTE', max_length=20)),
                ('tentatives_envoi', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('expire_le', models.DateTimeField(blank=True, null=True)),
                ('reference_objet', models.CharField(blank=True, max_length=255)),
                ('type_objet', models.CharField(blank=True, max_length=100)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['destinataire', 'statut'], name='notificatio_destina_47e387_idx'), models.Index(fields=['type_notification', 'date_creation'], name='notificatio_type_no_b5db7f_idx')],
            },
        ),
    ]
